<?xml version="1.0" encoding="utf-8"?><Database Name="triplethreatgame" Class="TripleThreatGameDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.0.1.33;Initial Catalog=triplethreatgame;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.chat" Member="chats">
    <Type Name="chat">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="chat" Member="chat1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.games" Member="games">
    <Type Name="game">
      <Column Name="game_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.scores" Member="scores">
    <Type Name="score">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="game_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="score" Member="score1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="win" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="player1" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="player2" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_OAuthMembership" Member="webpages_OAuthMemberships">
    <Type Name="webpages_OAuthMembership">
      <Column Name="Provider" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderUserId" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>